/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SGestionAnteproyectos.vistas;

import SGestionAnteproyectos.sop_rmi.GestionAnteproyectoImpl;
import SGestionAnteproyectos.sop_rmi.GestionUsuariosImpl;
import SGestionAnteproyectos.utilidades.UtilidadesRegistroS;

import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class GUIConectarServidor1 extends javax.swing.JFrame {

    /**
     * Creates new form GUIConectarServidor1
     */
    public GUIConectarServidor1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblConexion1 = new javax.swing.JLabel();
        lblIP1 = new javax.swing.JLabel();
        lblPuerto1 = new javax.swing.JLabel();
        btnConectar1 = new javax.swing.JButton();
        txtIP1 = new javax.swing.JTextField();
        txtPuerto1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Conectar servidor de gestion");

        jPanel1.setBackground(new java.awt.Color(0, 255, 204));
        jPanel1.setLayout(null);

        lblConexion1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lblConexion1.setText("CONEXION CON EL SERVIDOR");
        jPanel1.add(lblConexion1);
        lblConexion1.setBounds(0, 20, 240, 30);

        lblIP1.setText("Digite la direccion ip:");
        jPanel1.add(lblIP1);
        lblIP1.setBounds(10, 90, 140, 14);

        lblPuerto1.setText("Digite el  puerto:");
        jPanel1.add(lblPuerto1);
        lblPuerto1.setBounds(10, 170, 120, 14);

        btnConectar1.setText("Conectar");
        btnConectar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConectar1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnConectar1);
        btnConectar1.setBounds(110, 260, 90, 23);
        jPanel1.add(txtIP1);
        txtIP1.setBounds(200, 80, 100, 30);
        jPanel1.add(txtPuerto1);
        txtPuerto1.setBounds(200, 160, 100, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/conexion.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 400, 320);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConectar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConectar1ActionPerformed
      
 
        String MensajeRegistrar;
        String MensajeRecuperar;
        
        String MensajeRegistrarU;
        String MensajeRecuperarU;
        
        int puerto=Integer.parseInt(txtPuerto1.getText());
        String direccion=txtIP1.getText();
        try{
        GestionAnteproyectoImpl objetoRemoto = new  GestionAnteproyectoImpl();
        MensajeRecuperar=objetoRemoto.consultarReferenciaRemota(direccion, puerto);
        MensajeRegistrar=UtilidadesRegistroS.RegistrarObjetoRemoto(objetoRemoto, direccion, puerto, "objetoRemotoGestion");
        
        GestionUsuariosImpl objetoRemotoU = new  GestionUsuariosImpl();
        MensajeRecuperarU=objetoRemotoU.consultarReferenciaRemota(direccion, puerto);
        MensajeRegistrarU=UtilidadesRegistroS.RegistrarObjetoRemoto(objetoRemotoU, direccion, puerto, "objetoRemotoUsuario");
        
        GUIMensajesServidor1 GUIS1 =new GUIMensajesServidor1();
        GUIS1.setVisible(true);
        String mensaje=MensajeRecuperar+"\n"+MensajeRegistrar+"\n"+MensajeRegistrarU+"\n"+MensajeRecuperarU+"\n";
        GUIS1.txtMensaje1.setText(mensaje);     
        }catch(Exception e){
        JOptionPane.showMessageDialog(null,"No fue posible arrancar el NS o registrar el objeto remoto"+e.getMessage());
        }
    }//GEN-LAST:event_btnConectar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIConectarServidor1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIConectarServidor1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIConectarServidor1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIConectarServidor1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIConectarServidor1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConectar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblConexion1;
    private javax.swing.JLabel lblIP1;
    private javax.swing.JLabel lblPuerto1;
    private javax.swing.JTextField txtIP1;
    private javax.swing.JTextField txtPuerto1;
    // End of variables declaration//GEN-END:variables
}
