/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cliente.vistas;

import SGestionAnteproyectos.dto.clsFormatoTiBDTO;
import SGestionAnteproyectos.sop_rmi.GestionAnteproyectoINT;
import SGestionAnteproyectos.sop_rmi.GestionUsuariosINT;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class GUIAsignar extends javax.swing.JFrame {

    /**
     * Creates new form GUIAsignar
     */
    private static GestionAnteproyectoINT objetoRemotoAnteproyecto;
      private static GestionUsuariosINT objetoRemotoUsuario;
    public GUIAsignar(GestionAnteproyectoINT  objAnte,GestionUsuariosINT objUsuario) {
        initComponents();
        this.objetoRemotoAnteproyecto=objAnte;
        this.objetoRemotoUsuario=objUsuario;
    }
     public GUIAsignar(){}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblAsignarAn = new javax.swing.JLabel();
        lblCodigoAnt = new javax.swing.JLabel();
        lblIdEv1 = new javax.swing.JLabel();
        lblIdEv2 = new javax.swing.JLabel();
        btnAsignar = new javax.swing.JButton();
        txtCodAnt = new javax.swing.JTextField();
        txtCodEv1 = new javax.swing.JTextField();
        txtCodEv2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        lblAsignarAn.setText("Asignar Anteproyecto");

        lblCodigoAnt.setText("Codigo del anteproyecto");

        lblIdEv1.setText("id del evaluador 1:");

        lblIdEv2.setText("id del evaluador 2:");

        btnAsignar.setText("Asignar");
        btnAsignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCodigoAnt)
                    .addComponent(lblIdEv1)
                    .addComponent(lblIdEv2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCodEv1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodAnt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodEv2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(lblAsignarAn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAsignar)
                .addGap(144, 144, 144))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAsignarAn)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigoAnt)
                    .addComponent(txtCodAnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdEv1)
                    .addComponent(txtCodEv1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdEv2)
                    .addComponent(txtCodEv2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(btnAsignar)
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarActionPerformed
        int u1=-2;
        int u2=-2;
        int a=-2;
        if(txtCodAnt.getText().isEmpty() && txtCodEv1.getText().isEmpty() && txtCodEv2.getText().isEmpty()){
         JOptionPane.showMessageDialog(null, "Todos los campos son obligatorios");
        
        }
        else if( txtCodEv1.getText().equals(txtCodEv2.getText())){
             JOptionPane.showMessageDialog(null, "los id de los evaluadores deben ser diferentes");
        }else{
            int codigoAnte=Integer.parseInt(txtCodAnt.getText());
            int codEva1=Integer.parseInt( txtCodEv1.getText());
            int codEva2=Integer.parseInt( txtCodEv2.getText());
            try {
                a=objetoRemotoAnteproyecto.consultarAnteproyecto(codigoAnte);
                u1=objetoRemotoUsuario.consultarEvaluador(codEva1);
                u2=objetoRemotoUsuario.consultarEvaluador(codEva2);
                
                if(a==1 && u1==1 && u2==1){
                    clsFormatoTiBDTO objB1 = new clsFormatoTiBDTO(codEva1,codigoAnte,-1,"","");
                    clsFormatoTiBDTO objB2 = new clsFormatoTiBDTO(codEva2,codigoAnte,-1,"","");
                    boolean asignando1=objetoRemotoAnteproyecto.Asignar(objB1);
                    boolean asignando2=objetoRemotoAnteproyecto.Asignar(objB2);
                    
                    if(asignando1==true && asignando2==true){
                      JOptionPane.showMessageDialog(null, "Evaluadores asignados correctamente");
                    }
                }else if(a==-1){
                  JOptionPane.showMessageDialog(null, "No se encuentran Anteproyectos registrados ");
                }else if(a==0){
                    JOptionPane.showMessageDialog(null, "No se encuentra el anteproyecto regitrado ");
                }else if(a==2){
                    JOptionPane.showMessageDialog(null, "Al anteproyecto ya se le asignaron los evaluadores ");
                }else if(u1==-1){
                      JOptionPane.showMessageDialog(null, "No se encuentran Evaluadores registrados ");
                }else if(u1==2){
                      JOptionPane.showMessageDialog(null, "No existe este evaluador ");
                }
                
            } catch (RemoteException ex) {
                Logger.getLogger(GUIAsignar.class.getName()).log(Level.SEVERE, null, ex);
            }
           
        }
        
        
    }//GEN-LAST:event_btnAsignarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIAsignar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIAsignar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIAsignar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIAsignar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIAsignar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsignar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAsignarAn;
    private javax.swing.JLabel lblCodigoAnt;
    private javax.swing.JLabel lblIdEv1;
    private javax.swing.JLabel lblIdEv2;
    private javax.swing.JTextField txtCodAnt;
    private javax.swing.JTextField txtCodEv1;
    private javax.swing.JTextField txtCodEv2;
    // End of variables declaration//GEN-END:variables
}
