/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cliente.vistas;

import SGestionAnteproyectos.dto.clsUsuarioDTO;
import SGestionAnteproyectos.sop_rmi.GestionUsuariosINT;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class GUIConsultarUsuario extends javax.swing.JFrame {

    /**
     * Creates new form GUIConsultarUsuario
     */
    private static GestionUsuariosINT objetoRemotoUsuario;
    public GUIConsultarUsuario(GestionUsuariosINT objetoRemoto) {
        initComponents();
          this.objetoRemotoUsuario=objetoRemoto;
    }
     public GUIConsultarUsuario(){}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblConsultarUsuario = new javax.swing.JLabel();
        lblIdentifiacionConsultar = new javax.swing.JLabel();
        txtIndentificacionConsultar = new javax.swing.JTextField();
        btnConsultarU = new javax.swing.JButton();
        lblNombreComCon = new javax.swing.JLabel();
        lblRolCon = new javax.swing.JLabel();
        lblDepartamentoCon = new javax.swing.JLabel();
        lblUsuarioCon = new javax.swing.JLabel();
        lblNombreComSalida = new javax.swing.JLabel();
        lblRolConSalida = new javax.swing.JLabel();
        lblDepartamentoConSalida = new javax.swing.JLabel();
        lblUsuarioConSalida = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consultar Usuario");

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));

        lblConsultarUsuario.setText("Consultar Usuario");

        lblIdentifiacionConsultar.setText("Identificacion");

        btnConsultarU.setText("Consultar");
        btnConsultarU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarUActionPerformed(evt);
            }
        });

        lblNombreComCon.setText("Nombre Completo:");

        lblRolCon.setText("Rol:");

        lblDepartamentoCon.setText("Departamento:");

        lblUsuarioCon.setText("Usuario:");

        lblNombreComSalida.setText("-");

        lblRolConSalida.setText("-");

        lblDepartamentoConSalida.setText("-");

        lblUsuarioConSalida.setText("-");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIdentifiacionConsultar)
                    .addComponent(lblNombreComCon)
                    .addComponent(lblUsuarioCon)
                    .addComponent(lblDepartamentoCon)
                    .addComponent(lblRolCon))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblNombreComSalida)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtIndentificacionConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnConsultarU)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRolConSalida)
                            .addComponent(lblDepartamentoConSalida)
                            .addComponent(lblUsuarioConSalida))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(lblConsultarUsuario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblConsultarUsuario)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdentifiacionConsultar)
                    .addComponent(txtIndentificacionConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultarU))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreComCon)
                    .addComponent(lblNombreComSalida))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRolCon)
                    .addComponent(lblRolConSalida))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDepartamentoCon)
                    .addComponent(lblDepartamentoConSalida))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuarioCon)
                    .addComponent(lblUsuarioConSalida))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultarUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarUActionPerformed
   
        try {
            int id =Integer.parseInt(txtIndentificacionConsultar.getText());
            clsUsuarioDTO objUsuario=objetoRemotoUsuario.ConsultarUsuario(id);
            if(objUsuario!=null){

                lblNombreComSalida.setText(objUsuario.getNombreCompleto());
                lblRolConSalida.setText(objUsuario.getRole());
                lblUsuarioConSalida.setText(objUsuario.getUsuario());
                lblDepartamentoConSalida.setText(objUsuario.getDepartamento());
            }else{
              JOptionPane.showMessageDialog(null,"Usuario No encontrado");
            }
        } catch (RemoteException ex) {
            Logger.getLogger(GUIConsultarUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
      
    }//GEN-LAST:event_btnConsultarUActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIConsultarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIConsultarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIConsultarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIConsultarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIConsultarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultarU;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblConsultarUsuario;
    private javax.swing.JLabel lblDepartamentoCon;
    private javax.swing.JLabel lblDepartamentoConSalida;
    private javax.swing.JLabel lblIdentifiacionConsultar;
    private javax.swing.JLabel lblNombreComCon;
    private javax.swing.JLabel lblNombreComSalida;
    private javax.swing.JLabel lblRolCon;
    private javax.swing.JLabel lblRolConSalida;
    private javax.swing.JLabel lblUsuarioCon;
    private javax.swing.JLabel lblUsuarioConSalida;
    private javax.swing.JTextField txtIndentificacionConsultar;
    // End of variables declaration//GEN-END:variables
}
