/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cliente.vistas;

import SGestionAnteproyectos.dto.clsUsuarioDTO;
import SGestionAnteproyectos.sop_rmi.GestionUsuariosINT;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class GUIModificarUsuario extends javax.swing.JFrame {

    /**
     * Creates new form GUIModificarUsuario
     */
     private static GestionUsuariosINT objetoRemotoUsuario;
     private int Id;
    public GUIModificarUsuario(GestionUsuariosINT objetoRemoto) {
        initComponents();
         this.objetoRemotoUsuario=objetoRemoto;
    }
    public GUIModificarUsuario(){}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblModificarUsuario = new javax.swing.JLabel();
        lblIdentificacionMod = new javax.swing.JLabel();
        lblNombreComMod = new javax.swing.JLabel();
        lblRolMod = new javax.swing.JLabel();
        lblDepartamentoMod = new javax.swing.JLabel();
        lblContraseniaMod = new javax.swing.JLabel();
        txtIdentificacionMod = new javax.swing.JTextField();
        txtNombreComMod = new javax.swing.JTextField();
        txtDepartamentoMod = new javax.swing.JTextField();
        txtContraseniaMod = new javax.swing.JTextField();
        cmbRolMod = new javax.swing.JComboBox<>();
        btnModificarU = new javax.swing.JButton();
        btnBuscarMod = new javax.swing.JButton();
        lblUsuarioMod = new javax.swing.JLabel();
        txtUsuarioMod = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modificar Usuario");

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));

        lblModificarUsuario.setText("Modificar Usuario");

        lblIdentificacionMod.setText("Identificacion:");

        lblNombreComMod.setText("Nombre Completo:");

        lblRolMod.setText("Rol:");

        lblDepartamentoMod.setText("Departamento");

        lblContraseniaMod.setText("Contraseña:");

        cmbRolMod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Director", "Evaluador", "Jefe departamento\t", "Coordinador", "Decano" }));

        btnModificarU.setText("Modificar");
        btnModificarU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarUActionPerformed(evt);
            }
        });

        btnBuscarMod.setText("Buscar");
        btnBuscarMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarModActionPerformed(evt);
            }
        });

        lblUsuarioMod.setText("Usuario");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIdentificacionMod, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNombreComMod)
                            .addComponent(lblDepartamentoMod, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblContraseniaMod)
                            .addComponent(lblRolMod)
                            .addComponent(lblUsuarioMod))
                        .addGap(68, 68, 68)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtDepartamentoMod, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbRolMod, javax.swing.GroupLayout.Alignment.LEADING, 0, 1, Short.MAX_VALUE)
                            .addComponent(txtNombreComMod, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIdentificacionMod, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtContraseniaMod)
                            .addComponent(txtUsuarioMod, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addComponent(btnBuscarMod))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(lblModificarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(btnModificarU)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblModificarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdentificacionMod)
                    .addComponent(txtIdentificacionMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarMod))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreComMod)
                    .addComponent(txtNombreComMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRolMod)
                    .addComponent(cmbRolMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDepartamentoMod)
                    .addComponent(txtDepartamentoMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuarioMod)
                    .addComponent(txtUsuarioMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContraseniaMod)
                    .addComponent(txtContraseniaMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(btnModificarU)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarModActionPerformed
  
         try {
            Id=Integer.parseInt(txtIdentificacionMod.getText());
            clsUsuarioDTO objUsuario=objetoRemotoUsuario.ConsultarUsuario(Id);
              if(objUsuario!=null){ 
               txtContraseniaMod.setText(objUsuario.getContrasenia());
               txtDepartamentoMod.setText(objUsuario.getDepartamento());
               txtNombreComMod.setText(objUsuario.getNombreCompleto());
               cmbRolMod.setSelectedItem(objUsuario.getRole());
               txtUsuarioMod.setText(objUsuario.getUsuario());
              }else{
              JOptionPane.showMessageDialog(null,"Usuario No encontrado");
            } 
         } catch (RemoteException ex) {
             Logger.getLogger(GUIModificarUsuario.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_btnBuscarModActionPerformed

    private void btnModificarUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarUActionPerformed

        try {
             Id = Integer.parseInt(txtIdentificacionMod.getText());
            String Nombre = txtNombreComMod.getText();
            String Rol = (String) cmbRolMod.getSelectedItem();
            String Departamento = txtDepartamentoMod.getText();
            String Contrasenia = txtContraseniaMod.getText();
            String Usuario = txtUsuarioMod.getText();
            clsUsuarioDTO objUsuario = new clsUsuarioDTO(Id, Nombre, Rol, Departamento, Usuario, Contrasenia);

            boolean funciono = objetoRemotoUsuario.ModificarUsuario(objUsuario);
            if (funciono == true) {
                JOptionPane.showMessageDialog(null, "Usuario Modificado exitosamente");
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "El usuario no se pudo Modificar con exito");
                this.dispose();
            }
            this.dispose();
        } catch (RemoteException ex) {
            Logger.getLogger(GUIModificarUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btnModificarUActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIModificarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIModificarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIModificarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIModificarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIModificarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarMod;
    private javax.swing.JButton btnModificarU;
    private javax.swing.JComboBox<String> cmbRolMod;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblContraseniaMod;
    private javax.swing.JLabel lblDepartamentoMod;
    private javax.swing.JLabel lblIdentificacionMod;
    private javax.swing.JLabel lblModificarUsuario;
    private javax.swing.JLabel lblNombreComMod;
    private javax.swing.JLabel lblRolMod;
    private javax.swing.JLabel lblUsuarioMod;
    private javax.swing.JTextField txtContraseniaMod;
    private javax.swing.JTextField txtDepartamentoMod;
    private javax.swing.JTextField txtIdentificacionMod;
    private javax.swing.JTextField txtNombreComMod;
    private javax.swing.JTextField txtUsuarioMod;
    // End of variables declaration//GEN-END:variables
}
