/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cliente.vistas;

import SGestionAnteproyectos.sop_rmi.GestionAnteproyectoINT;
import SGestionAnteproyectos.sop_rmi.GestionUsuariosINT;
import SSeguimientoAnteproyectos.sop_rmi.GestionSeguimientoINT;

/**
 *
 * @author Usuario
 */
public class GUIMenuDecano extends javax.swing.JFrame {

    /**
     * Creates new form GUIMenuDecano
     */
    private static GestionAnteproyectoINT objetoRemotoAnteproyecto;
    private static GestionUsuariosINT objetoRemotoUsuario;
    private static GestionSeguimientoINT objetoRemotoSeguimiento;

    public GUIMenuDecano(GestionUsuariosINT objUsuario, GestionAnteproyectoINT objAnteproyecto, GestionSeguimientoINT objRemotoSeg) {
        initComponents();
        this.objetoRemotoUsuario = objUsuario;
        this.objetoRemotoAnteproyecto = objAnteproyecto;
        this.objetoRemotoSeguimiento = objRemotoSeg;
    }

    public GUIMenuDecano() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblMenuDecano = new javax.swing.JLabel();
        btnRegistrarR = new javax.swing.JButton();
        btnConHistorial = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnAprobados = new javax.swing.JButton();
        btnAprobadosCoor = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMenuDecano.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lblMenuDecano.setText("Menu Decano");
        jPanel1.add(lblMenuDecano, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 40, 146, -1));

        btnRegistrarR.setText("Registrar Resolucion");
        btnRegistrarR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarRActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrarR, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 92, 211, -1));

        btnConHistorial.setText("Consultar Historial TGI");
        btnConHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConHistorialActionPerformed(evt);
            }
        });
        jPanel1.add(btnConHistorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 133, 211, -1));

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 244, -1, -1));

        btnAprobados.setText("Consultar Listado TGI Aprobados");
        btnAprobados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAprobadosActionPerformed(evt);
            }
        });
        jPanel1.add(btnAprobados, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 174, 211, -1));

        btnAprobadosCoor.setText("Listado aprobados por el coordinador");
        btnAprobadosCoor.setToolTipText("");
        btnAprobadosCoor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAprobadosCoorActionPerformed(evt);
            }
        });
        jPanel1.add(btnAprobadosCoor, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 210, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/decano.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 280));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        GUIInicioSesion GUISesion = new GUIInicioSesion(objetoRemotoUsuario, objetoRemotoAnteproyecto, objetoRemotoSeguimiento);
        GUISesion.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnAprobadosCoorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAprobadosCoorActionPerformed
        GUIListarAprobadosD objListD = new GUIListarAprobadosD(objetoRemotoAnteproyecto);
        objListD.setVisible(true);
    }//GEN-LAST:event_btnAprobadosCoorActionPerformed

    private void btnRegistrarRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarRActionPerformed
        GUIRResolucion objR = new GUIRResolucion(objetoRemotoAnteproyecto, objetoRemotoSeguimiento);
        objR.setVisible(true);
    }//GEN-LAST:event_btnRegistrarRActionPerformed

    private void btnAprobadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAprobadosActionPerformed
        GUIConsultarResolucion objCR = new GUIConsultarResolucion(objetoRemotoAnteproyecto, objetoRemotoSeguimiento);
        objCR.setVisible(true);
    }//GEN-LAST:event_btnAprobadosActionPerformed

    private void btnConHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConHistorialActionPerformed
        GUIConsultarHistorial objH = new GUIConsultarHistorial(objetoRemotoAnteproyecto, objetoRemotoSeguimiento);
        objH.setVisible(true);
    }//GEN-LAST:event_btnConHistorialActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIMenuDecano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIMenuDecano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIMenuDecano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIMenuDecano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIMenuDecano().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAprobados;
    private javax.swing.JButton btnAprobadosCoor;
    private javax.swing.JButton btnConHistorial;
    private javax.swing.JButton btnRegistrarR;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblMenuDecano;
    // End of variables declaration//GEN-END:variables
}
