/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cliente.vistas;

import SGestionAnteproyectos.dto.clsUsuarioDTO;
import SGestionAnteproyectos.sop_rmi.GestionAnteproyectoINT;
import SGestionAnteproyectos.sop_rmi.GestionUsuariosINT;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class GUIRegistrarUsuario extends javax.swing.JFrame {

    /**
     * Creates new form RegistrarAdmin
     */

    private static GestionUsuariosINT objetoRemotoUsuario;
    public GUIRegistrarUsuario(GestionUsuariosINT objetoRemoto) {
        initComponents();
        this.objetoRemotoUsuario=objetoRemoto;
    }
    public GUIRegistrarUsuario(){}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblRegistrarUsuario = new javax.swing.JLabel();
        lblIdentificacionU = new javax.swing.JLabel();
        lblNombreComU = new javax.swing.JLabel();
        lblRolU = new javax.swing.JLabel();
        lblDepartamentoU = new javax.swing.JLabel();
        lblUsuarioU = new javax.swing.JLabel();
        lblContraseniaU = new javax.swing.JLabel();
        txtIdentificacionU = new javax.swing.JTextField();
        txtNombreComU = new javax.swing.JTextField();
        txtDepartamentoU = new javax.swing.JTextField();
        txtUsuarioU = new javax.swing.JTextField();
        txtContraseniaU = new javax.swing.JTextField();
        btnRegistrarU = new javax.swing.JButton();
        cmbRolU = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registrar Usuario");

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        lblRegistrarUsuario.setText("Registrar Usuario");

        lblIdentificacionU.setText("Identificacion:");

        lblNombreComU.setText("Nombre Completo:");

        lblRolU.setText("rol:");

        lblDepartamentoU.setText("Departamento:");

        lblUsuarioU.setText("Usuario:");

        lblContraseniaU.setText("contraseña:");

        btnRegistrarU.setText("Registrar");
        btnRegistrarU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarUActionPerformed(evt);
            }
        });

        cmbRolU.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Director", "Evaluador", "Jefe departamento", "Coordinador", "Decano" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblRegistrarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(131, 131, 131))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIdentificacionU)
                    .addComponent(lblContraseniaU)
                    .addComponent(lblUsuarioU)
                    .addComponent(lblDepartamentoU)
                    .addComponent(lblRolU)
                    .addComponent(lblNombreComU))
                .addGap(100, 100, 100)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDepartamentoU, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                    .addComponent(txtUsuarioU)
                    .addComponent(txtContraseniaU)
                    .addComponent(txtIdentificacionU)
                    .addComponent(txtNombreComU)
                    .addComponent(cmbRolU, 0, 1, Short.MAX_VALUE))
                .addGap(66, 66, 66))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(btnRegistrarU)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRegistrarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIdentificacionU)
                    .addComponent(txtIdentificacionU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombreComU)
                    .addComponent(txtNombreComU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRolU)
                    .addComponent(cmbRolU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDepartamentoU)
                    .addComponent(txtDepartamentoU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUsuarioU)
                    .addComponent(txtUsuarioU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblContraseniaU)
                    .addComponent(txtContraseniaU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(btnRegistrarU)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarUActionPerformed
    
        try {
        int id=Integer.parseInt(txtIdentificacionU.getText());
        String NombreCompleto=txtNombreComU.getText();
        String Rol=(String) cmbRolU.getSelectedItem();
        String Departamento=txtDepartamentoU.getText();
        String Usuario=txtUsuarioU.getText();
        String Contrasenia=(String) txtContraseniaU.getText();
        clsUsuarioDTO objUsuario=new clsUsuarioDTO(id,NombreCompleto,Rol,Departamento,Usuario,Contrasenia);
        boolean funciono =objetoRemotoUsuario.RegistrarUsuarios(objUsuario);
        if(funciono==true){
            JOptionPane.showMessageDialog(null,"Usuario registrado exitosamente");
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null,"El usuario no se pudo Registrar con exito");
             this.dispose();
        }
        this.dispose();
        } catch (RemoteException ex) {
        
            Logger.getLogger(GUIRegistrarUsuario.class.getName()).log(Level.SEVERE, null, ex);
             this.dispose();
        }
    }//GEN-LAST:event_btnRegistrarUActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIRegistrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIRegistrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIRegistrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIRegistrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIRegistrarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarU;
    private javax.swing.JComboBox<String> cmbRolU;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblContraseniaU;
    private javax.swing.JLabel lblDepartamentoU;
    private javax.swing.JLabel lblIdentificacionU;
    private javax.swing.JLabel lblNombreComU;
    private javax.swing.JLabel lblRegistrarUsuario;
    private javax.swing.JLabel lblRolU;
    private javax.swing.JLabel lblUsuarioU;
    private javax.swing.JTextField txtContraseniaU;
    private javax.swing.JTextField txtDepartamentoU;
    private javax.swing.JTextField txtIdentificacionU;
    private javax.swing.JTextField txtNombreComU;
    private javax.swing.JTextField txtUsuarioU;
    // End of variables declaration//GEN-END:variables
}
