/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cliente.vistas;

import SGestionAnteproyectos.sop_rmi.GestionAnteproyectoINT;
import SGestionAnteproyectos.dto.clsFormatoTiBDTO;
import java.rmi.RemoteException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class GUIRFormatoB extends javax.swing.JFrame {

    /**
     * Creates new form GURIFormatoB
     */
    private static GestionAnteproyectoINT objetoRemotoAnteproyecto;
    private int idEv;

    public GUIRFormatoB(GestionAnteproyectoINT objAnte, int idv) {
        initComponents();
        this.objetoRemotoAnteproyecto = objAnte;
        this.idEv = idv;
    }

    public GUIRFormatoB() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblEvaluarAnt = new javax.swing.JLabel();
        lblCodigoAnt = new javax.swing.JLabel();
        lblConceptoEv = new javax.swing.JLabel();
        lblObsevaciones = new javax.swing.JLabel();
        lblFechaEvaluacion = new javax.swing.JLabel();
        btnEvaluar = new javax.swing.JButton();
        txtObservaciones = new javax.swing.JTextField();
        txtCodAnt = new javax.swing.JTextField();
        cmbConcepto = new javax.swing.JComboBox<>();
        jdFechaEvaluacion = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblEvaluarAnt.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lblEvaluarAnt.setText("Evaluar Anteproyecto");
        jPanel1.add(lblEvaluarAnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 11, -1, -1));

        lblCodigoAnt.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        lblCodigoAnt.setText("Codigo del Anteproyecto");
        jPanel1.add(lblCodigoAnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 170, -1));

        lblConceptoEv.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        lblConceptoEv.setText("Concepto");
        jPanel1.add(lblConceptoEv, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 90, -1));

        lblObsevaciones.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        lblObsevaciones.setText("Observaciones");
        jPanel1.add(lblObsevaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 110, -1));

        lblFechaEvaluacion.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        lblFechaEvaluacion.setText("Fecha Evaluacion");
        lblFechaEvaluacion.setToolTipText("");
        jPanel1.add(lblFechaEvaluacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 130, -1));

        btnEvaluar.setText("Evaluar");
        btnEvaluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEvaluarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEvaluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 214, -1, -1));
        jPanel1.add(txtObservaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 119, 59, -1));

        txtCodAnt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodAntKeyTyped(evt);
            }
        });
        jPanel1.add(txtCodAnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 43, 59, -1));

        cmbConcepto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aprobado", "Reprobado" }));
        jPanel1.add(cmbConcepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 90, -1));
        jPanel1.add(jdFechaEvaluacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/b.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 270));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEvaluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEvaluarActionPerformed
        if (txtCodAnt.getText().isEmpty() || jdFechaEvaluacion.getDate()==null|| txtObservaciones.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Todos los campos deben ser ingresados");
        } else {

            int CodigoAnt = Integer.parseInt(txtCodAnt.getText());
            int Concepto;
            String con = (String) cmbConcepto.getSelectedItem();
            if (con.equals("Aprobado")) {
                Concepto = 1;
            } else {
                Concepto = 0;
            }

            String Observaciones = txtObservaciones.getText();
            Date FechaCalendar = jdFechaEvaluacion.getDate();
            String Fecha = String.valueOf(FechaCalendar);
            
            clsFormatoTiBDTO objB = new clsFormatoTiBDTO(idEv, CodigoAnt, Concepto, Observaciones, Fecha);
            try {
                boolean funciono = objetoRemotoAnteproyecto.verificarPropiedad(CodigoAnt, idEv);
                int funciono2 = objetoRemotoAnteproyecto.VerificarAnteproyecto(CodigoAnt);

                if (funciono2 >= 3) {
                    JOptionPane.showMessageDialog(null, "Ya se realizaron las evaluaciones para este anteproyecto");
                    this.dispose();
                } else if (funciono2 == 0) {
                    JOptionPane.showMessageDialog(null, "No se encontro Anteproyecto");
                    this.dispose();
                } else if (funciono == false) {
                    JOptionPane.showMessageDialog(null, "No puede evaluar anteproyectos que no le han sido asignado");
                    this.dispose();
                } else {
                    boolean funciono3 = objetoRemotoAnteproyecto.RegistrarFormatoTiB(objB);
                    if (funciono3 == true) {
                        JOptionPane.showMessageDialog(null, "Anteproyecto evaluado exitosamente");
                        this.dispose();
                    } else {
                        JOptionPane.showMessageDialog(null, "Usted ya emitio un concepto para este anteproyecto");
                        this.dispose();
                    }
                }

            } catch (RemoteException ex) {
                Logger.getLogger(GUIRFormatoB.class.getName()).log(Level.SEVERE, null, ex);
            }
        }


    }//GEN-LAST:event_btnEvaluarActionPerformed

    private void txtCodAntKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodAntKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_txtCodAntKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIRFormatoB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIRFormatoB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIRFormatoB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIRFormatoB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIRFormatoB().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEvaluar;
    private javax.swing.JComboBox<String> cmbConcepto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private com.toedter.calendar.JDateChooser jdFechaEvaluacion;
    private javax.swing.JLabel lblCodigoAnt;
    private javax.swing.JLabel lblConceptoEv;
    private javax.swing.JLabel lblEvaluarAnt;
    private javax.swing.JLabel lblFechaEvaluacion;
    private javax.swing.JLabel lblObsevaciones;
    private javax.swing.JTextField txtCodAnt;
    private javax.swing.JTextField txtObservaciones;
    // End of variables declaration//GEN-END:variables
}
