/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cliente.vistas;

import SGestionAnteproyectos.dto.clsFormatoTiADTO;
import SGestionAnteproyectos.sop_rmi.GestionAnteproyectoINT;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class GUIRFormatoA extends javax.swing.JFrame {

    /**
     * Creates new form GUIRFormatoA
     */
  
    private static GestionAnteproyectoINT objetoRemotoAnteproyecto;
    public GUIRFormatoA(GestionAnteproyectoINT  objAnte) {
        initComponents();
        this.objetoRemotoAnteproyecto=objAnte;
        try {
            this.lblCodigoASalida.setText(Integer.toString(this.objetoRemotoAnteproyecto.solicitarCodigo()));
        } catch (RemoteException ex) {
            Logger.getLogger(GUIRFormatoA.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
      public GUIRFormatoA(){}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblRegistrarAnte = new javax.swing.JLabel();
        lblNombrePrograma = new javax.swing.JLabel();
        lblTituloAnteproyecto = new javax.swing.JLabel();
        lblNombreEst01 = new javax.swing.JLabel();
        lblNombreEst02 = new javax.swing.JLabel();
        lblCodigo01 = new javax.swing.JLabel();
        lblCodigo02 = new javax.swing.JLabel();
        lblNombreDir = new javax.swing.JLabel();
        lblNombreCodir = new javax.swing.JLabel();
        lblObjetivos = new javax.swing.JLabel();
        lblCodigoA = new javax.swing.JLabel();
        txtTituloA = new javax.swing.JTextField();
        txtNombreEst01 = new javax.swing.JTextField();
        txtCodigoEst01 = new javax.swing.JTextField();
        txtNombreEst02 = new javax.swing.JTextField();
        txtCodigoEst02 = new javax.swing.JTextField();
        txtNombreDir = new javax.swing.JTextField();
        txtNombreCoodir = new javax.swing.JTextField();
        btnRegistrarA = new javax.swing.JButton();
        txtNombrePA = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObjetivos = new javax.swing.JTextArea();
        lblCodigoASalida = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));

        lblRegistrarAnte.setText("Registrar Anteproyecto");

        lblNombrePrograma.setText("Nombre del programa");

        lblTituloAnteproyecto.setText("Titulo Anteproyecto");

        lblNombreEst01.setText("Nombre estudiante01");

        lblNombreEst02.setText("Nombre estudiante02");

        lblCodigo01.setText("Codigo01");

        lblCodigo02.setText("Codigo02");

        lblNombreDir.setText("Nombre Director");

        lblNombreCodir.setText("Nombre Co-director");

        lblObjetivos.setText("Objetivos del anteproyecto");

        lblCodigoA.setText("Codigo");

        btnRegistrarA.setText("Registrar");
        btnRegistrarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarAActionPerformed(evt);
            }
        });

        txtObjetivos.setColumns(20);
        txtObjetivos.setRows(5);
        jScrollPane1.setViewportView(txtObjetivos);

        lblCodigoASalida.setText("-");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombreCodir)
                            .addComponent(lblNombrePrograma)
                            .addComponent(lblCodigoA)
                            .addComponent(lblTituloAnteproyecto)
                            .addComponent(lblNombreEst01)
                            .addComponent(lblCodigo01)
                            .addComponent(lblNombreEst02)
                            .addComponent(lblCodigo02)
                            .addComponent(lblNombreDir))
                        .addGap(192, 192, 192)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombreCoodir, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombreDir, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodigoEst02, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombreEst02, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtTituloA, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                                .addComponent(txtNombreEst01)
                                .addComponent(txtCodigoEst01)
                                .addComponent(txtNombrePA))
                            .addComponent(lblCodigoASalida)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblRegistrarAnte)
                            .addComponent(lblObjetivos))))
                .addContainerGap(103, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(btnRegistrarA))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRegistrarAnte)
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigoA)
                    .addComponent(lblCodigoASalida))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombrePA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombrePrograma))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTituloAnteproyecto)
                    .addComponent(txtTituloA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreEst01)
                    .addComponent(txtNombreEst01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigo01, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigoEst01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreEst02)
                    .addComponent(txtNombreEst02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigoEst02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCodigo02))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(lblObjetivos))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombreDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNombreDir))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombreCoodir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNombreCodir))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(btnRegistrarA)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarAActionPerformed

        try {
            if(lblCodigoASalida.getText().isEmpty() || txtNombrePA.getText().isEmpty() ||  txtTituloA.getText().isEmpty() && txtNombreEst01.getText().isEmpty() || txtCodigoEst01.getText().isEmpty() || txtNombreDir.getText().isEmpty() || txtNombreCoodir.getText().isEmpty() || txtObjetivos.getText().isEmpty() || txtNombreEst02.getText().isEmpty() || txtCodigoEst02.getText().isEmpty()){
               JOptionPane.showMessageDialog(null, "Todos los campos deben ser ingresados");
            }else{
            int codigo = Integer.parseInt(lblCodigoASalida.getText());
            String NombreP = txtNombrePA.getText();
            String TituloA = txtTituloA.getText();
            String NombreEst1 = txtNombreEst01.getText();
            int Codigo1 = Integer.parseInt(txtCodigoEst01.getText());
            String NombreEst2 = txtNombreEst02.getText();
            int Codigo2 = Integer.parseInt(txtCodigoEst02.getText());
            String NombreDir = txtNombreDir.getText();
            String NombreCoodir = txtNombreCoodir.getText();
            String Objetivos =txtObjetivos.getText();
            clsFormatoTiADTO objFormatoA = new clsFormatoTiADTO(codigo, NombreP, TituloA, NombreEst1, Codigo1, NombreEst2, Codigo2, NombreDir, NombreCoodir, Objetivos);
            boolean funciono = objetoRemotoAnteproyecto.RegistrarFormatoTiA(objFormatoA);
            if (funciono == true) {
                JOptionPane.showMessageDialog(null, "Anteproyecto registrado exitosamente");
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "El Anteproyecto no se pudo Registrar con exito");
                this.dispose();
            }
            }
            
        } catch (RemoteException ex) {
            Logger.getLogger(GUIRFormatoA.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRegistrarAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIRFormatoA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIRFormatoA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIRFormatoA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIRFormatoA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIRFormatoA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarA;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCodigo01;
    private javax.swing.JLabel lblCodigo02;
    private javax.swing.JLabel lblCodigoA;
    private javax.swing.JLabel lblCodigoASalida;
    private javax.swing.JLabel lblNombreCodir;
    private javax.swing.JLabel lblNombreDir;
    private javax.swing.JLabel lblNombreEst01;
    private javax.swing.JLabel lblNombreEst02;
    private javax.swing.JLabel lblNombrePrograma;
    private javax.swing.JLabel lblObjetivos;
    private javax.swing.JLabel lblRegistrarAnte;
    private javax.swing.JLabel lblTituloAnteproyecto;
    private javax.swing.JTextField txtCodigoEst01;
    private javax.swing.JTextField txtCodigoEst02;
    private javax.swing.JTextField txtNombreCoodir;
    private javax.swing.JTextField txtNombreDir;
    private javax.swing.JTextField txtNombreEst01;
    private javax.swing.JTextField txtNombreEst02;
    private javax.swing.JTextField txtNombrePA;
    private javax.swing.JTextArea txtObjetivos;
    private javax.swing.JTextField txtTituloA;
    // End of variables declaration//GEN-END:variables
}
