/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cliente.vistas;

import SGestionAnteproyectos.dto.clsFormatoTiDDTO;
import SGestionAnteproyectos.sop_rmi.GestionAnteproyectoINT;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class GUIRFormatoD extends javax.swing.JFrame {

    /**
     * Creates new form GUIRFormatoD
     */
    private static GestionAnteproyectoINT objetoRemotoAnteproyecto;
    private static String depCoor;

    public GUIRFormatoD(GestionAnteproyectoINT objAnteproyecto, String depCoor) {
        initComponents();
        this.objetoRemotoAnteproyecto = objAnteproyecto;
        this.depCoor = depCoor;
        this.cmbConcepto.setEnabled(false);
        this.txtEstructura.setEnabled(false);
        this.txtObservaciones.setEnabled(false);
        this.btnEvaluar.setEnabled(false);
    }

    public GUIRFormatoD() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblEvaluarAnt = new javax.swing.JLabel();
        lblCodigoAnt = new javax.swing.JLabel();
        lblEstructura = new javax.swing.JLabel();
        lblConcepto = new javax.swing.JLabel();
        lblObservaciones = new javax.swing.JLabel();
        txtEstructura = new javax.swing.JTextField();
        btnEvaluar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObservaciones = new javax.swing.JTextArea();
        txtCodigoAnt = new javax.swing.JTextField();
        btnValidar = new javax.swing.JButton();
        cmbConcepto = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblEvaluarAnt.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lblEvaluarAnt.setText("Evaluar Anteproyecto");
        jPanel1.add(lblEvaluarAnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 200, -1));

        lblCodigoAnt.setText("Codigo Anteproyecto");
        jPanel1.add(lblCodigoAnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 52, -1, -1));

        lblEstructura.setText("Estructura");
        jPanel1.add(lblEstructura, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 92, -1, -1));

        lblConcepto.setText("Concepto");
        jPanel1.add(lblConcepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 130, -1, -1));

        lblObservaciones.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lblObservaciones.setText("Observaciones");
        jPanel1.add(lblObservaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 165, 120, -1));
        jPanel1.add(txtEstructura, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 89, 73, -1));

        btnEvaluar.setText("Evaluar");
        btnEvaluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEvaluarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEvaluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 307, -1, -1));

        txtObservaciones.setColumns(20);
        txtObservaciones.setRows(5);
        jScrollPane1.setViewportView(txtObservaciones);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 190, 190, 106));

        txtCodigoAnt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoAntKeyTyped(evt);
            }
        });
        jPanel1.add(txtCodigoAnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 49, 73, -1));

        btnValidar.setText("Validar");
        btnValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidarActionPerformed(evt);
            }
        });
        jPanel1.add(btnValidar, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 48, -1, -1));

        cmbConcepto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aprobado", "Reprobado" }));
        jPanel1.add(cmbConcepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 90, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/d.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 470));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEvaluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEvaluarActionPerformed
        if (txtCodigoAnt.getText().isEmpty() || txtEstructura.getText().isEmpty() || txtObservaciones.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Todos los campos deben ser ingresados");
        } else {
            try {
                int codAnt = Integer.parseInt(txtCodigoAnt.getText());
                String estructura = txtEstructura.getText();
                String Observaciones = txtObservaciones.getText();

                int concepto;
                String con = (String) cmbConcepto.getSelectedItem();
                if (con.equals("Aprobado")) {
                    concepto = 1;
                } else {
                    concepto = 0;
                }

                clsFormatoTiDDTO objD = new clsFormatoTiDDTO(codAnt, estructura, concepto, Observaciones);

                boolean funciono = objetoRemotoAnteproyecto.RegistrarFormatoTiD(objD);
                if (funciono == true) {
                    JOptionPane.showMessageDialog(null, "EL Anteproyecto ha sido evaluado con exito");
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "El Anteproyecto no ha sido evaluado con exito");
                    this.dispose();
                }

            } catch (RemoteException ex) {
                Logger.getLogger(GUIRFormatoC.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnEvaluarActionPerformed

    private void btnValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidarActionPerformed

        if (txtCodigoAnt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor ingresa el codigo");
        } else {

            try {
                int flujo = objetoRemotoAnteproyecto.VerificarAnteproyecto(Integer.parseInt(txtCodigoAnt.getText()));
                int concepto = objetoRemotoAnteproyecto.ConsultarConceptoJefe(Integer.parseInt(txtCodigoAnt.getText()));
                boolean departamentoCorrecto = false;
                departamentoCorrecto = this.objetoRemotoAnteproyecto.verificarRemitidoDep(Integer.parseInt(txtCodigoAnt.getText()), depCoor);
                if (concepto == 1 && departamentoCorrecto && flujo == 4) {
                    this.cmbConcepto.setEnabled(true);
                    this.txtEstructura.setEnabled(true);
                    this.txtObservaciones.setEnabled(true);
                    this.btnEvaluar.setEnabled(true);
                } else if (flujo == 0) {
                    JOptionPane.showMessageDialog(null, "No se encontro Anteproyecto");
                    this.dispose();
                } else if (flujo < 4) {
                    JOptionPane.showMessageDialog(null, "El Anteproyecto todavia no ha sido evaluado por el jefe de departamentp");
                    this.dispose();
                } else if (flujo == 5) {
                    JOptionPane.showMessageDialog(null, "El  Anteproyecto ya fue evaluado por el coordinador");
                    this.dispose();
                } else if (departamentoCorrecto == false) {
                    JOptionPane.showMessageDialog(null, "El  Anteproyecto no correcponde a este departamento");
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "El Anteproyecto no fue aprobado por el jede de departamento");

                    this.dispose();
                }

            } catch (RemoteException ex) {
                Logger.getLogger(GUIRFormatoD.class.getName()).log(Level.SEVERE, null, ex);
            }

        }


    }//GEN-LAST:event_btnValidarActionPerformed

    private void txtCodigoAntKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoAntKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }

    }//GEN-LAST:event_txtCodigoAntKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIRFormatoD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIRFormatoD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIRFormatoD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIRFormatoD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIRFormatoD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEvaluar;
    private javax.swing.JButton btnValidar;
    private javax.swing.JComboBox<String> cmbConcepto;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCodigoAnt;
    private javax.swing.JLabel lblConcepto;
    private javax.swing.JLabel lblEstructura;
    private javax.swing.JLabel lblEvaluarAnt;
    private javax.swing.JLabel lblObservaciones;
    private javax.swing.JTextField txtCodigoAnt;
    private javax.swing.JTextField txtEstructura;
    private javax.swing.JTextArea txtObservaciones;
    // End of variables declaration//GEN-END:variables
}
