/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cliente.vistas;

import SGestionAnteproyectos.sop_rmi.GestionAnteproyectoINT;
import SGestionAnteproyectos.dto.clsFormatoTiBDTO;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author Usuario
 */
public class GUIRFormatoB extends javax.swing.JFrame {

    /**
     * Creates new form GURIFormatoB
     */
    private static GestionAnteproyectoINT objetoRemotoAnteproyecto;
    private int idEv;
    public GUIRFormatoB(GestionAnteproyectoINT  objAnte, int idv) {
        initComponents();
         this.objetoRemotoAnteproyecto=objAnte;
         this.idEv=idEv;
    }
 public GUIRFormatoB(){}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblEvaluarAnt = new javax.swing.JLabel();
        lblCodigoAnt = new javax.swing.JLabel();
        lblConceptoEv = new javax.swing.JLabel();
        lblObsevaciones = new javax.swing.JLabel();
        lblFechaEvaluacion = new javax.swing.JLabel();
        btnEvaluar = new javax.swing.JButton();
        txtObservaciones = new javax.swing.JTextField();
        txtConceptoEv = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        txtCodAnt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        lblEvaluarAnt.setText("Evaluar Anteproyecto");

        lblCodigoAnt.setText("Codigo del Anteproyecto");

        lblConceptoEv.setText("Concepto");

        lblObsevaciones.setText("Observaciones");

        lblFechaEvaluacion.setText("Fecha Evaluacion");
        lblFechaEvaluacion.setToolTipText("");

        btnEvaluar.setText("Evaluar");
        btnEvaluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEvaluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblEvaluarAnt)
                .addGap(133, 133, 133))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblObsevaciones)
                    .addComponent(lblFechaEvaluacion)
                    .addComponent(lblCodigoAnt)
                    .addComponent(lblConceptoEv))
                .addGap(118, 118, 118)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtFecha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                    .addComponent(txtConceptoEv, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtObservaciones, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCodAnt))
                .addGap(63, 63, 63))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(btnEvaluar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEvaluarAnt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigoAnt)
                    .addComponent(txtCodAnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblConceptoEv)
                    .addComponent(txtConceptoEv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblObsevaciones)
                    .addComponent(txtObservaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaEvaluacion)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(btnEvaluar)
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEvaluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEvaluarActionPerformed
        if (txtCodAnt.getText().isEmpty() && txtConceptoEv.getText().isEmpty() && txtFecha.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "EL unico campo no obligatorio son las observaciones");
        } else {

            int CodigoAnt = Integer.parseInt(txtCodAnt.getText());
            int Concepto = Integer.parseInt(txtConceptoEv.getText());
            String Observaciones = txtObservaciones.getText();
            String Fecha = txtFecha.getText();
            clsFormatoTiBDTO objB = new clsFormatoTiBDTO(idEv, CodigoAnt, Concepto, Observaciones, Fecha);
            try {
                boolean funciono = objetoRemotoAnteproyecto.verificarPropiedad(CodigoAnt, idEv);
                int funciono2 = objetoRemotoAnteproyecto.VerificarAnteproyecto(CodigoAnt);
                
                if(funciono2>=3){
                     JOptionPane.showMessageDialog(null, "ya se realizaron las evaluaciones para este anteproyecto");
                }else if(funciono==false){
                        JOptionPane.showMessageDialog(null, "No puede evaluar anteproyectos que no le han sido asignados");
                }else{
                   boolean funciono3 =objetoRemotoAnteproyecto.RegistrarFormatoTiB(objB);
                   
                   if(funciono3==true){
                     JOptionPane.showMessageDialog(null, "Anteproyecto evaluado exitosamente");
                   }else{
                        JOptionPane.showMessageDialog(null, "El Anteproyecto No se logro evaluar");
                   }
                }

            } catch (RemoteException ex) {
                Logger.getLogger(GUIRFormatoB.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

      
    }//GEN-LAST:event_btnEvaluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIRFormatoB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIRFormatoB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIRFormatoB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIRFormatoB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIRFormatoB().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEvaluar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCodigoAnt;
    private javax.swing.JLabel lblConceptoEv;
    private javax.swing.JLabel lblEvaluarAnt;
    private javax.swing.JLabel lblFechaEvaluacion;
    private javax.swing.JLabel lblObsevaciones;
    private javax.swing.JTextField txtCodAnt;
    private javax.swing.JTextField txtConceptoEv;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtObservaciones;
    // End of variables declaration//GEN-END:variables
}
